[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"


[[headers]]
  for = "/_next/static/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/hero-bg.jpg"
  [headers.values]
    cache-control = "public, max-age=86400, stale-while-revalidate=604800"

[[headers]]
  for = "/logo.svg"
  [headers.values]
    cache-control = "public, max-age=86400, stale-while-revalidate=604800"
