-- ==============================================================================
-- Mahbub College: Simplified Supabase Schema & Seed Data
-- Features:
-- - Simple auto-increment integer IDs (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)
-- - Completely CSV-friendly: `id` is optional on CSV import
-- - Removed unnecessary fields: `description`, `created_at`
-- - Simplified names: `title` (was designation), `batch` (was batch_or_era)
-- ==============================================================================

-- 1. Former Students Who Made Us Proud
CREATE TABLE IF NOT EXISTS public.former_students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    title TEXT NOT NULL,
    batch TEXT,
    photo_url TEXT,
    display_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT true
);

-- 2. The Leaders Who Shaped Our Institution
CREATE TABLE IF NOT EXISTS public.leaders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    title TEXT NOT NULL,
    era TEXT,
    photo_url TEXT,
    display_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT true
);

-- 3. Our Heritage, Our Pride
CREATE TABLE IF NOT EXISTS public.heritage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    photo_url TEXT NOT NULL,
    display_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT true
);

-- 4. The People Who Built Our Legacy
CREATE TABLE IF NOT EXISTS public.legacy_builders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    title TEXT NOT NULL,
    period TEXT,
    photo_url TEXT,
    display_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT true
);

-- 5. News and Updates
CREATE TABLE IF NOT EXISTS public.news_and_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    secondary_text TEXT,
    photo_url TEXT,
    published_date DATE DEFAULT CURRENT_DATE,
    external_link TEXT,
    display_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT true
);

-- 6. Gallery
CREATE TABLE IF NOT EXISTS public.gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    caption TEXT,
    year_or_era TEXT,
    category TEXT DEFAULT 'Campus',
    photo_url TEXT NOT NULL,
    display_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT true
);

-- 7. Alumni Registrations Form Submissions
CREATE TABLE IF NOT EXISTS public.registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    batch TEXT,
    profession TEXT,
    city TEXT,
    message TEXT,
    status TEXT DEFAULT 'new',
    created_at TIMESTAMPTZ DEFAULT now()
);

-- ------------------------------------------------------------------------------
-- Row Level Security (RLS)
-- ------------------------------------------------------------------------------
ALTER TABLE public.former_students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leaders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.heritage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.legacy_builders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news_and_updates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.registrations ENABLE ROW LEVEL SECURITY;

-- Public read policies
DO $$
BEGIN
    DROP POLICY IF EXISTS "Allow public read on former_students" ON public.former_students;
    CREATE POLICY "Allow public read on former_students" ON public.former_students FOR SELECT USING (is_active = true);

    DROP POLICY IF EXISTS "Allow public read on leaders" ON public.leaders;
    CREATE POLICY "Allow public read on leaders" ON public.leaders FOR SELECT USING (is_active = true);

    DROP POLICY IF EXISTS "Allow public read on heritage" ON public.heritage;
    CREATE POLICY "Allow public read on heritage" ON public.heritage FOR SELECT USING (is_active = true);

    DROP POLICY IF EXISTS "Allow public read on legacy_builders" ON public.legacy_builders;
    CREATE POLICY "Allow public read on legacy_builders" ON public.legacy_builders FOR SELECT USING (is_active = true);

    DROP POLICY IF EXISTS "Allow public read on news_and_updates" ON public.news_and_updates;
    CREATE POLICY "Allow public read on news_and_updates" ON public.news_and_updates FOR SELECT USING (is_active = true);

    DROP POLICY IF EXISTS "Allow public read on gallery" ON public.gallery;
    CREATE POLICY "Allow public read on gallery" ON public.gallery FOR SELECT USING (is_active = true);

    DROP POLICY IF EXISTS "Allow public insert on registrations" ON public.registrations;
    CREATE POLICY "Allow public insert on registrations" ON public.registrations FOR INSERT WITH CHECK (true);
END $$;

-- ------------------------------------------------------------------------------
-- Baseline Seed Data: 11 Former Students from Figma
-- ------------------------------------------------------------------------------
INSERT INTO public.former_students (name, title, batch, photo_url, display_order)
VALUES
  ('Admiral Ram Dass Katari', 'Chief of Naval Staff (CNS)', '1928', '/media/former_students/admiral_ram_dass_katari.png', 1),
  ('Air Marshal P.J Jayakumar', 'Vice Chief of Air Staff', '1958', '/media/former_students/air_marshal_pj_jayakumar.png', 2),
  ('M. Shambunath Singh', 'Commander Indian Navy', '1962', '/media/former_students/m_shambunath_singh.png', 3),
  ('Justice M. S. K Jaiswal', 'Judge, High Court of Telangana & President', '1968', '/media/former_students/justice_msk_jaiswal.png', 4),
  ('Dr. Mohan Kanda', 'IAS Officer and Former Chief Secretary (AP)', '1961', '/media/former_students/dr_mohan_kanda.png', 5),
  ('Srinivas Anandaraman', 'Former Director-General of Police', '1971', '/media/former_students/srinivas_anandaraman.png', 6),
  ('M. L. Jaisimha', 'Former Indian Test Cricketer', '1954', '/media/former_students/ml_jaisimha.png', 7),
  ('N. Mukesh Kumar', 'Former Indian Field Hockey Player', '1984', '/media/former_students/n_mukesh_kumar.png', 8),
  ('Shyam Benegal', 'Film Director & Screenwriter', '1950', '/media/former_students/shyam_benegal.png', 9),
  ('Col. T. Mahesh Kumar', '1970 Batch', '1970', '/media/former_students/col_t_mahesh_kumar.png', 10),
  ('MANEK S. MADON', '1970 BATCH', '1970', '/media/former_students/manek_s_madon.png', 11)
ON CONFLICT DO NOTHING;

-- ------------------------------------------------------------------------------
-- 8. Supabase Storage Bucket: 'media' (Public)
-- ------------------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'media',
  'media',
  true,
  52428800, -- 50MB
  ARRAY['image/png', 'image/jpeg', 'image/jpg', 'image/webp', 'image/svg+xml']
)
ON CONFLICT (id) DO UPDATE SET 
  public = true,
  file_size_limit = 52428800;

-- Storage Policies for 'media' bucket
DO $$
BEGIN
    DROP POLICY IF EXISTS "Public Access Media Bucket" ON storage.objects;
    CREATE POLICY "Public Access Media Bucket" 
    ON storage.objects 
    FOR SELECT 
    USING (bucket_id = 'media');

    DROP POLICY IF EXISTS "Admin Upload Media Bucket" ON storage.objects;
    CREATE POLICY "Admin Upload Media Bucket" 
    ON storage.objects 
    FOR INSERT 
    TO authenticated 
    WITH CHECK (bucket_id = 'media');

    DROP POLICY IF EXISTS "Admin Update Media Bucket" ON storage.objects;
    CREATE POLICY "Admin Update Media Bucket" 
    ON storage.objects 
    FOR UPDATE 
    TO authenticated 
    USING (bucket_id = 'media');

    DROP POLICY IF EXISTS "Admin Delete Media Bucket" ON storage.objects;
    CREATE POLICY "Admin Delete Media Bucket" 
    ON storage.objects 
    FOR DELETE 
    TO authenticated 
    USING (bucket_id = 'media');
END $$;
